import 'package:flutter/material.dart' as flutter;

/// Contains all colors of the Rings of the Magic Raibow Ball.
enum Ring {
  WHITE,
  BLACK,
  LIGHT_GREEN,
  DARK_GREEN,
  LIGHT_BLUE,
  DARK_BLUE,
  YELLOW,
  ORANGE,
  RED,
  PINK,
  PURPLE,
  CYAN,
}

extension RingExtension on Ring {
  List<Ring> get neighbors => neighborMap[this];

  int distance(Ring ring) => distanceMap[this][ring];

  flutter.Color get color => colors[this];
}

/// Assigns every ring a color, which is usable in Flutter.
Map<Ring, flutter.Color> colors = {
  Ring.WHITE : flutter.Colors.grey,
  Ring.BLACK : flutter.Colors.black,
  Ring.LIGHT_GREEN : flutter.Colors.lightGreen,
  Ring.DARK_GREEN : flutter.Colors.green,
  Ring.LIGHT_BLUE : flutter.Colors.lightBlue,
  Ring.DARK_BLUE : flutter.Colors.blue,
  Ring.YELLOW : flutter.Colors.yellow,
  Ring.ORANGE : flutter.Colors.orange,
  Ring.RED : flutter.Colors.red,
  Ring.PINK : flutter.Colors.pink,
  Ring.PURPLE : flutter.Colors.purple,
  Ring.CYAN : flutter.Colors.cyan,
};

/// Contains information regarding every Rings neighbors.
Map<Ring, List<Ring>> neighborMap = {
  Ring.WHITE: [Ring.PURPLE, Ring.LIGHT_BLUE, Ring.BLACK, Ring.CYAN, Ring.DARK_BLUE],
  Ring.BLACK: [Ring.WHITE, Ring.LIGHT_BLUE, Ring.RED, Ring.YELLOW, Ring.CYAN],
  Ring.LIGHT_GREEN: [Ring.ORANGE, Ring.PINK, Ring.DARK_BLUE, Ring.CYAN, Ring.YELLOW],
  Ring.DARK_GREEN: [Ring.PURPLE, Ring.PINK, Ring.ORANGE, Ring.RED, Ring.LIGHT_BLUE],
  Ring.LIGHT_BLUE: [Ring.WHITE, Ring.PURPLE, Ring.DARK_GREEN, Ring.RED, Ring.BLACK],
  Ring.DARK_BLUE: [Ring.PINK, Ring.PURPLE, Ring.WHITE, Ring.CYAN, Ring.LIGHT_GREEN],
  Ring.YELLOW: [Ring.BLACK, Ring.RED, Ring.ORANGE, Ring.LIGHT_GREEN, Ring.CYAN],
  Ring.ORANGE: [Ring.PINK, Ring.LIGHT_GREEN, Ring.YELLOW, Ring.RED, Ring.DARK_GREEN],
  Ring.RED: [Ring.BLACK, Ring.LIGHT_BLUE, Ring.DARK_GREEN, Ring.ORANGE, Ring.YELLOW],
  Ring.PINK: [Ring.DARK_GREEN, Ring.PURPLE, Ring.DARK_BLUE, Ring.LIGHT_GREEN, Ring.ORANGE],
  Ring.PURPLE: [Ring.LIGHT_BLUE, Ring.WHITE, Ring.DARK_BLUE, Ring.PINK, Ring.DARK_GREEN],
  Ring.CYAN: [Ring.LIGHT_GREEN, Ring.DARK_BLUE, Ring.WHITE, Ring.BLACK, Ring.YELLOW],
};

/// Contains the distances between each and every Ring.
Map<Ring, Map<Ring, int>> distanceMap = {
  Ring.WHITE: {
    Ring.WHITE: 0,
    Ring.BLACK: 1,
    Ring.LIGHT_GREEN: 2,
    Ring.DARK_GREEN: 2,
    Ring.LIGHT_BLUE: 1,
    Ring.DARK_BLUE: 1,
    Ring.YELLOW: 2,
    Ring.ORANGE: 3,
    Ring.RED: 2,
    Ring.PINK: 2,
    Ring.PURPLE: 1,
    Ring.CYAN: 1,
  },
  Ring.BLACK: {
    Ring.WHITE: 1,
    Ring.BLACK: 0,
    Ring.LIGHT_GREEN: 2,
    Ring.DARK_GREEN: 2,
    Ring.LIGHT_BLUE: 1,
    Ring.DARK_BLUE: 2,
    Ring.YELLOW: 1,
    Ring.ORANGE: 2,
    Ring.RED: 1,
    Ring.PINK: 3,
    Ring.PURPLE: 2,
    Ring.CYAN: 1,
  },
  Ring.LIGHT_GREEN: {
    Ring.WHITE: 2,
    Ring.BLACK: 2,
    Ring.LIGHT_GREEN: 0,
    Ring.DARK_GREEN: 2,
    Ring.LIGHT_BLUE: 3,
    Ring.DARK_BLUE: 1,
    Ring.YELLOW: 1,
    Ring.ORANGE: 1,
    Ring.RED: 2,
    Ring.PINK: 1,
    Ring.PURPLE: 2,
    Ring.CYAN: 1,
  },
  Ring.DARK_GREEN: {
    Ring.WHITE: 2,
    Ring.BLACK: 2,
    Ring.LIGHT_GREEN: 2,
    Ring.DARK_GREEN: 0,
    Ring.LIGHT_BLUE: 1,
    Ring.DARK_BLUE: 2,
    Ring.YELLOW: 2,
    Ring.ORANGE: 1,
    Ring.RED: 1,
    Ring.PINK: 1,
    Ring.PURPLE: 1,
    Ring.CYAN: 3,
  },
  Ring.LIGHT_BLUE: {
    Ring.WHITE: 1,
    Ring.BLACK: 1,
    Ring.LIGHT_GREEN: 3,
    Ring.DARK_GREEN: 1,
    Ring.LIGHT_BLUE: 0,
    Ring.DARK_BLUE: 2,
    Ring.YELLOW: 2,
    Ring.ORANGE: 2,
    Ring.RED: 1,
    Ring.PINK: 2,
    Ring.PURPLE: 1,
    Ring.CYAN: 2,
  },
  Ring.DARK_BLUE: {
    Ring.WHITE: 1,
    Ring.BLACK: 2,
    Ring.LIGHT_GREEN: 1,
    Ring.DARK_GREEN: 2,
    Ring.LIGHT_BLUE: 2,
    Ring.DARK_BLUE: 0,
    Ring.YELLOW: 2,
    Ring.ORANGE: 2,
    Ring.RED: 3,
    Ring.PINK: 1,
    Ring.PURPLE: 1,
    Ring.CYAN: 1,
  },
  Ring.YELLOW: {
    Ring.WHITE: 2,
    Ring.BLACK: 1,
    Ring.LIGHT_GREEN: 1,
    Ring.DARK_GREEN: 2,
    Ring.LIGHT_BLUE: 2,
    Ring.DARK_BLUE: 2,
    Ring.YELLOW: 0,
    Ring.ORANGE: 1,
    Ring.RED: 1,
    Ring.PINK: 2,
    Ring.PURPLE: 3,
    Ring.CYAN: 1,
  },
  Ring.ORANGE: {
    Ring.WHITE: 3,
    Ring.BLACK: 2,
    Ring.LIGHT_GREEN: 1,
    Ring.DARK_GREEN: 1,
    Ring.LIGHT_BLUE: 2,
    Ring.DARK_BLUE: 2,
    Ring.YELLOW: 1,
    Ring.ORANGE: 0,
    Ring.RED: 1,
    Ring.PINK: 1,
    Ring.PURPLE: 2,
    Ring.CYAN: 2,
  },
  Ring.RED: {
    Ring.WHITE: 2,
    Ring.BLACK: 1,
    Ring.LIGHT_GREEN: 2,
    Ring.DARK_GREEN: 1,
    Ring.LIGHT_BLUE: 1,
    Ring.DARK_BLUE: 3,
    Ring.YELLOW: 1,
    Ring.ORANGE: 1,
    Ring.RED: 0,
    Ring.PINK: 2,
    Ring.PURPLE: 2,
    Ring.CYAN: 2,
  },
  Ring.PINK: {
    Ring.WHITE: 2,
    Ring.BLACK: 3,
    Ring.LIGHT_GREEN: 1,
    Ring.DARK_GREEN: 1,
    Ring.LIGHT_BLUE: 2,
    Ring.DARK_BLUE: 1,
    Ring.YELLOW: 2,
    Ring.ORANGE: 1,
    Ring.RED: 2,
    Ring.PINK: 0,
    Ring.PURPLE: 1,
    Ring.CYAN: 2,
  },
  Ring.PURPLE: {
    Ring.WHITE: 1,
    Ring.BLACK: 2,
    Ring.LIGHT_GREEN: 2,
    Ring.DARK_GREEN: 1,
    Ring.LIGHT_BLUE: 1,
    Ring.DARK_BLUE: 1,
    Ring.YELLOW: 3,
    Ring.ORANGE: 2,
    Ring.RED: 2,
    Ring.PINK: 1,
    Ring.PURPLE: 0,
    Ring.CYAN: 2,
  },
  Ring.CYAN: {
    Ring.WHITE: 1,
    Ring.BLACK: 1,
    Ring.LIGHT_GREEN: 1,
    Ring.DARK_GREEN: 3,
    Ring.LIGHT_BLUE: 2,
    Ring.DARK_BLUE: 1,
    Ring.YELLOW: 1,
    Ring.ORANGE: 2,
    Ring.RED: 2,
    Ring.PINK: 2,
    Ring.PURPLE: 2,
    Ring.CYAN: 0,
  },
};
